---
- name: Install and configure tomcat server for deployment
  hosts: nodes

  tasks:
    - name: Update system package
      apt:
       upgrade: yes
       update_cache: yes

    - name: Install Java
      apt:
       name: openjdk-11-jdk
       state: present

    - name: Check Java Version
      command: java --version

    - name: Create Tomcat User
      user:
       name: tomcat

    - name: Create Tomcat Group
      group:
       name: tomcat

    - name: Create Tomcat Directory
      file:
       path: "/opt/tomcat"
       owner: tomcat
       group: tomcat
       mode: 755
       recurse: yes

    - name: Download Tomcat and Unarchive
      unarchive:
       src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.5/bin/apache-tomcat-10.1.5.tar.gz
       dest: /opt/tomcat
       remote_src: yes
       extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat folder
      file:
       path: /opt/tomcat


    - name: Change ownership of tomcat folder
      command: sh /opt/tomcat/bin/startup.sh 

    - name: Allow tcp connections
      command: sudo ufw allow 8080/tcp
